sass:
  quiet_deps: true

#includes
include: [_pages]

#personal info
title: Into My Mind
email: juanpablobecerra103@gmail.com

# Build settings
theme: minimal-mistakes-jekyll 
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-tagories
minimal_mistakes_skin: "dark"

#default configs

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      show_date: true
      published: false
      permalink: :categories/:title

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      permalink: "/:basename/"

  - scope: 
      type: portfolio
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      breadcrumbs: true
      show_date: true
      published: false
      toc: true
      toc_sticky: true
  - scope:
      path: ""
      type: tag
    values:
      breadcrumbs: true
      title: "tag"
  - scope:
      path: ""
      type: category
    values:
      title: "category"
      breadcrumbs: true

breadcrumbs: true

category_archive:
  type: jekyll-archives
  path: categories/
tag_archive:
  type: jekyll-archives
  path: /tags/

jekyll-archives:
    enabled:
      - categories
      - tags
    layouts:
      category: archive-taxonomy
      tag: archive-taxonomy
    permalinks:
      category: categories/:name/
      tag: tags/:name/









#setup

markdown: kramdown
kramdown:
  math_engine: mathjax

url: "https://juanpbp03.github.io/"
baseurl: ""  # Leave this blank unless you're using a subdirectory

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-FQY9KHBSSQ"
    anonymize_ip: false # default

author:
  name     : "Juan Pablo Becerra-Padilla"
  avatar   : "/assets/images/author-photo.jpg"
  bio      : "Somewhere between control systems and controlled chaos."
  location : "Mississauga, Ontario"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "/contact/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/juanpbp/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JuanPBP03/"
      
      
