#includes
include: [_pages]

#personal info
title: Into My Mind
email: juanpablobecerra103@gmail.com

# Build settings
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-include-cache
minimal_mistakes_skin: "dark"

#default configs

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      read_time: true
    # _pages

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      permalink: "/:basename/"

#setup
url: "https://www.juanpbp03.github.io"
baseurl: ""  # Leave this blank unless you're using a subdirectory

collections_dir: collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-FQY9KHBSSQ"
    anonymize_ip: false # default

author:
  name     : "Juan Pablo Becerra-Padilla"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "My awesome biography constrained to a sentence or two goes here."
  location : "Mississauga, Ontario"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "juanpablobecerra103@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/juanpbp"
    - label: "Phone"
      icon: "fas fa-fw fa-phone-square"
      url: "(647)-201-8034"
      
